name: GitHub Actions Demo - Search
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    paths:
      - 'search/**'

env:
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  PINECONE_NAMESPACE: ${{ github.sha }}
  PINECONE_INDEX_NAME: "search-ci"
  DATA_FILE: "search/data.jsonl"

jobs:
  Run-Search-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Print all environment variables
      run: env
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run data pipeline - upsert
      run: python search/data_pipeline.py upsert
    - name: Run unit tests
      run: python -m unittest search.test_app
  Teardown-Search-Tests-Fail:
    runs-on: ubuntu-latest
    needs: Run-Search-Tests
    if: always()
    steps:
    - name: Run data pipeline - delete
      run: python search/data_pipeline.py delete

