name: GitHub Actions Demo - Search
run-name: Search - ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on: 
  push:
    paths:
      - 'search/**'

env:
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  PINECONE_NAMESPACE: ${{ github.sha }}
  PINECONE_INDEX_NAME: "search-ci"
  DATA_FILE: "data/search-data.jsonl"

jobs:
  Build-RunDataPipeline-RunTests-Teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run data pipeline - upsert
        run: python search/data_pipeline.py upsert
      - name: Run search tests
        run: python -m unittest search.test_app
      - name: Run data pipeline - delete
        if: always()
        run: python search/data_pipeline.py delete