name: GitHub Actions Demo - Search
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on: 
  push:
    paths:
      - 'search/**'

env:
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  PINECONE_NAMESPACE: ${{ github.sha }}
  PINECONE_INDEX_NAME: "search-ci"
  DATA_FILE: "search/data.jsonl"

jobs:
  Install-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
  Run-Data-Pipeline:
    runs-on: ubuntu-latest
    needs: Install-Dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run data pipeline - upsert
        run: python search/data_pipeline.py upsert
  Run-Search-Tests:
    runs-on: ubuntu-latest
    needs: Run-Data-Pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run search tests
        run: python -m unittest search.test_app
  Teardown-Search-Data:
    runs-on: ubuntu-latest
    needs: Run-Search-Tests
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run data pipeline - delete
        run: python search/data_pipeline.py delete

